Update yaml to generate report via Github Pages, update Readme file

diff --git a/.github/workflows/bookstore-api-tests.yaml b/.github/workflows/bookstore-api-tests.yaml
--- a/.github/workflows/bookstore-api-tests.yaml
+++ b/.github/workflows/bookstore-api-tests.yaml
@@ -11,7 +11,7 @@ on:
   workflow_dispatch:      
     inputs:
       tags:
-        description: 'Test tags to run (e.g., negative, positive, edge)'
+        description: 'Test tags to run (e.g. positive, negative, edge)'
         required: false
         default: ''
       baseUrl:
@@ -66,20 +66,48 @@ jobs:
               bookstore-api-tests
           fi
 
+      # 5.1 Ensure previous run artifacts are removed (avoid mixing results)
+      - name: Clean previous Allure outputs
+        if: always()
+        run: |
+          rm -rf ./allure-results || true
+          rm -rf ./allure-report || true
+
       # 6. Copy Allure test results from container to host
       - name: Copy Allure results
         if: always()
         run: docker cp bookstore-tests:/app/target/allure-results ./allure-results
 
-      # 7. Upload Allure results as artifact (available in GitHub Actions UI)
-      - name: Upload Allure Results
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: allure-results
-          path: ./allure-results
 
-        # 8. Clean up Docker container
+      # 7. Generate Allure HTML report
+      - name: Generate Allure HTML report
+        if: always()
+        run: |
+          npm install -g allure-commandline --save-dev
+          allure generate ./allure-results --clean -o ./allure-report
+
+      # 8. Upload Allure HTML report as artifact (available in GitHub Actions UI)
+      # - name: Upload Allure HTML report
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: allure-html-report
+      #     path: ./allure-report
+      - name: Deploy Allure report to GitHub Pages
+        if: always()
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          publish_dir: ./allure-report
+
+      # 9. Clean up Docker container
       - name: Cleanup container
         if: always()
         run: docker rm -f bookstore-tests || true
+
+      # 10. Print Allure report link
+      - name: Show Allure Report Link
+        if: always()
+        run: |
+          echo "Here is your report: https://MajaTrajkovska.github.io/bookstore-api-tests/"
+          echo "Here is your report: https://MajaTrajkovska.github.io/bookstore-api-tests/" >> $GITHUB_STEP_SUMMARY
